let selected=null;
async function api(path,opts={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...opts});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');return d}
async function createBug(){await api('/bugs',{method:'POST',body:JSON.stringify({title:title.value,description:description.value,repository:repo.value,reporter:reporter.value})});title.value='';description.value='';await refresh()}
async function refresh(){const [bugs,m]=await Promise.all([api('/bugs'),api('/metrics')]);document.getElementById('bugs').innerHTML=bugs.map(b=>`<div class="bug" onclick="showBug(${b.id})"><b>#${b.id} ${b.title}</b><br><span class="badge">${b.status}</span> · iteration ${b.current_iteration}</div>`).join('')||'No bugs';document.getElementById('metrics').innerHTML=`<div class="metric"><b>Resolved</b><br>${m.resolved}/${m.total}</div><div class="metric"><b>First try</b><br>${(m.first_attempt_fix_rate*100).toFixed(0)}%</div><div class="metric"><b>Avg iterations</b><br>${m.avg_iterations.toFixed(1)}</div><div class="metric"><b>Change requests</b><br>${m.change_requests}</div>`}
async function showBug(id){selected=await api('/bugs/'+id);render()}
function render(){const b=selected;if(!b)return;const latest=b.iterations?.[b.iterations.length-1];document.getElementById('detail').innerHTML=`<h3>#${b.id} — ${b.title}</h3><p>${b.description}</p><p><b>Status:</b> <span class="badge">${b.status}</span></p><p><b>Root cause:</b> ${b.root_cause||'Not analyzed yet'}</p><p><b>Relevant files:</b> ${(b.relevant_files||[]).join(', ')||'—'}</p>${latest?`<h4>Iteration ${latest.number}</h4><p>${latest.plan.join('<br>')}</p><h4>Patch</h4><pre class="diff">${escapeHtml(latest.patch)}</pre><h4>Validation</h4><pre class="diff ${latest.validation.passed?'pass':'fail'}">${escapeHtml(JSON.stringify(latest.validation,null,2))}</pre>`:''}<div>${b.status==='NEW'?'<button onclick="action(\'/analyze\')">Start AI Analysis</button>':''}${b.status==='AWAITING_REVIEW'?'<button onclick="approve()">Approve & Merge</button><button onclick="feedback()">Request Changes</button>':''}</div><h4>History</h4>${(b.history||[]).map(x=>`<div>• ${x.timestamp} — <b>${x.event}</b> ${x.message||''}</div>`).join('')}`}
function escapeHtml(s){return (s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
async function action(path){await api('/bugs/'+selected.id+path,{method:'POST'});await showBug(selected.id);await refresh()}
async function approve(){await action('/approve')}
async function feedback(){const f=prompt('Developer feedback / requested changes:');if(f)await api('/bugs/'+selected.id+'/feedback',{method:'POST',body:JSON.stringify({feedback:f,developer:'developer'})});await showBug(selected.id);await refresh()}
refresh();setInterval(refresh,5000)
